import type { Metadata } from 'next'
import { Montserrat, Inter } from 'next/font/google'
import './globals.css'
import Image from 'next/image'

const montserrat = Montserrat({ subsets: ['latin'], variable: "--font-montserrat"})
const inter = Inter({ subsets: ['latin'], variable: "--font-inter"})

export const metadata: Metadata = {
  title: 'Diary App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${montserrat.variable} ${inter.variable} flex items-center flex-col mt-10 bg-neutral-900 `}>
        <Image src="/images/logo.png" width={200} height={200} alt='my diary' />
        {children}</body>
    </html>
  )
}
